// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

function assertNonEmptyEnv(name: string, value: unknown): asserts value is string {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new Error(
      `[supabase] Missing env var ${name}. Add it to .env/.env.development and restart the dev server.`
    );
  }
}

function assertValidUrl(name: string, value: string): void {
  try {
    // eslint-disable-next-line no-new
    new URL(value);
  } catch {
    throw new Error(`[supabase] Invalid URL in ${name}: ${JSON.stringify(value)}`);
  }
}

assertNonEmptyEnv('VITE_SUPABASE_URL', SUPABASE_URL);
assertNonEmptyEnv('VITE_SUPABASE_PUBLISHABLE_KEY', SUPABASE_PUBLISHABLE_KEY);
assertValidUrl('VITE_SUPABASE_URL', SUPABASE_URL);

const fetchWithTimeout: typeof fetch = async (input, init) => {
  const controller = new AbortController();
  const timeoutMs = 15000;
  const timeoutId = window.setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(input, { ...init, signal: controller.signal });
  } catch (error) {
    // Make timeouts more actionable in dev.
    if (error instanceof DOMException && error.name === 'AbortError') {
      throw new Error(
        `[supabase] Request timed out after ${timeoutMs}ms. Check your network/VPN/DNS and that ${SUPABASE_URL} is reachable.`
      );
    }
    throw error;
  } finally {
    window.clearTimeout(timeoutId);
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: fetchWithTimeout,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});